<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.servers.js'); ?>
<div class="panel panel-default">
    <div class="panel-heading collapsed" data-toggle="collapse" data-target="#factfilter"><span class="glyphicon glyphicon-search"></span><span class="panel-break"></span><?php echo $this->translate("Filter servers by fact") ?></div>
    <div class="panel-body collapse" id="factfilter">
        <form class="form-horizontal" action="">
            <fieldset class="col-sm-12">
                <div class="form-group">
                    <label class="control-label" for="fact"><?php echo $this->translate('Fact') ?></label>
                    <div class="controls row">
                        <div class="col-lg-4">
                            <select id="fact" data-placeholder="<?php echo $this->translate('Select a fact...') ?>" class="form-control" name="fact" data-rel="chosen">
                                <option value="default"></option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="value"><?php echo $this->translate('Value') ?></label>
                    <div class="controls row">
                        <div class="col-lg-4">
                            <input type="text" class="form-control" name="value" id="value" placeholder="<?php echo $this->translate('Enter a value for the fact') ?>">
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary" id="fact-filter-submit"><?php echo $this->translate('Search') ?></button>
                    <button type="reset" class="btn" id="fact-filter-reset"><?php echo $this->translate('Cancel') ?></button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><span class="glyphicon glyphicon-tasks"></span><span class="panel-break"></span><?php echo $this->translate('PuppetDB servers inventory') ?></div>
    <div class="panel-body">
        <form class="form-inline" role="form" id="set-environment-form" action="<?php echo $this->url('servers', ['action' => 'assign-to-environment'], [], true) ?>" method="post">
            <?php echo $this->datatable('servers_datatable')->renderHtml(); ?>
            <p class="note pull-right"><strong>*</strong> <?php echo $this->translate('fields available to search'); ?></p>
            <?php if ($this->isGranted('assignServersToEnv')): ?>
            <div class="input-group">
                <select id="environment" class="form-control" name="environment" data-placeholder="<?php echo $this->translate('Assign to environment') ?>" data-rel="chosen" style="display: none;">
                    <option></option>
                    <?php echo $this->environmentSelect('readEnv') ?>
                </select>
                <div class="input-group-btn">
                    <button class="btn btn-primary" type="submit"><?php echo $this->translate('OK') ?></button>
                </div>
            </div>
            <?php endif ?>
        </form>
    </div>
</div>
