<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.servers.js'); ?>
<div class="row">
    <div class="col-md-12">
        <div><?php echo $this->translate('Detailed informations on server') ?></div>
        <div class="date"><?php echo $this->escapeHtml($this->node->getName()) ?></div>
    </div>
</div>
<div class="row">
    <?php if (isset($this->back)): ?>
    <div class="col-md-2 info-bar pull-left">
        <div>&nbsp;</div>
        <div class="stats-title"><a href="<?php echo $this->escapeHtmlAttr($this->back) ?>" class="btn btn-info"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('back') ?></a></div>
    </div>
    <?php endif ?>
    <div class="col-md-2 info-bar pull-right">
        <div class="yellow" id="uptime_server"><?php echo $this->escapeHtml($this->node->getFact('uptime_days')) ?> <?php echo $this->translatePlural('day', 'days', $this->node->getFact('uptime_days')) ?></div>
        <div class="stats-title"><button class="btn btn-warning btn-disabled"><?php echo $this->translate('uptime') ?></button></div>
    </div>
    <?php echo $this->widget('serverInfoBar')->render(); ?>
</div>
<hr/>
<div class="row">
    <div class="col-sm-12">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#facts-list" role="tab" data-toggle="tab"><?php echo $this->translate('Server facts'); ?></a></li>
            <?php echo $this->widget('serverTabTitle')->render(); ?>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="facts-list">
                <table class="table table-striped table-hover table-condensed bootstrap-datatable datatable" id="facts">
                    <thead>
                    <tr>
                        <th><?php echo $this->translate('Fact') ?></th>
                        <th><?php echo $this->translate('Value') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <?php echo $this->widget('serverTabContent')->render(); ?>
        </div>
    </div>
</div>
